#!/usr/bin/env node

/**
 * Pre-build script to generate version.ts from package.json.
 * This allows the telemetry module to access the package version
 * without importing package.json directly.
 */

const fs = require('fs');
const path = require('path');

// Read package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

// Generate version.ts content
const versionTsContent = `/**
 * Package version - Auto-generated by scripts/prebuild.cjs
 * DO NOT EDIT THIS FILE MANUALLY
 */

export const VERSION = '${version}';
`;

// Write version.ts to src directory
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');
fs.writeFileSync(versionTsPath, versionTsContent, 'utf8');

console.log(`✓ Generated src/version.ts with version ${version}`);
